### ISSUE TITLE
Language for Supplier List

### ISSUE THREAD

**Issue by Toddses** [RainyDayMedia/techhub#34]
We also have 'Directions' copy on the Supplier List View. See screenshot.

![screen shot 2015-09-21 at 4 46 57 pm](https://cloud.githubusercontent.com/assets/7013826/10004584/777cc6b4-6080-11e5-8a2e-0ab0c2a97401.png)

**Comment by Toddses** [comment]
@jonathanhauge Still need language for this section.

**Comment by Toddses** [comment]
Since we're supposed to be finishing up Phase 1 today, and there is no response on this, I'm going to Backlog it.

**Comment by jonathanhauge** [comment]
Sounds good, thank you.
ᐧ

-- 
Jonathan Hauge


marketing - branding - design - communications - digital

*A 2012 BBB Eclipse Integrity Award Finalist*

937 / 490-4005
1360 Technology Court  |  Suite 300  |  Beavercreek, OH 45430
www.baldwincreative.com

Confidentiality Notice: This email message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message.

**Comment by ginfuru** [comment]
@jonathanhauge  you're gay
