### ISSUE TITLE
Table View

### ISSUE THREAD

**Issue by ginfuru** [RainyDayMedia/techhub#4]
#### Create list view of entries

[ ] table layout
   [ ] filters
[ ] single entry details
[ ] table buttons 
   [ ] csv/xls

**Comment by ginfuru** [comment]
@Toddses 
   Just making sure that you want a comp for the table layout or would you rather I create a UI Guide instead.

**Comment by Toddses** [comment]
I guess a comp. Since it’s the other main part of the app, a good starting point for the UI would be useful.

**Comment by Toddses** [comment]
can bounce this issue over to me when ready for dev
