### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/techhub#45]
After they saw the screenshots, these were the "instructions" provided for the "homepage."

The Tech Hub supplier database is a tool for the MEP Supplier Scouting initiative. MEP Supplier  Scouting effectively identifies domestic manufacturers that meet specifications and connects them with the supply chains of large companies.

Knowing the Ohio suppliers means understanding the opportunities for business. The database will help Ohio MEP match suppliers with procurement opportunities, generating more business.

How to use it?

By searching supplier profiles: When you are looking for specific capabilities (ie, thermoplastic thermoforming), you can use the database search engine to identify who in Ohio has these capabilities.

By adding/updating a supplier profile: When you visit a supplier or discover interesting capabilities through news articles etc, please create a supplier profile or update the existing one.

What is the scope of this database?
Currently limited to Ohio suppliers with CNC machining and advanced manufacturing capabilities.  Only non-proprietary and open distribution information should be included.

Can I update all supplier profiles?
Yes 

Who can see the data?
Only MEP affiliates

Who to contact if I have a question?
FASTLANE@udri.udayton.edu
937-229-1368

**Comment by jonathanhauge** [comment]
I don't know where they expect this information to go as there is currently no spot for something like this. 

I can ask for clarity and where they believed it should go to figure out what they are thinking.

**Comment by Toddses** [comment]
Cool.

**Comment by Toddses** [comment]
I'm going to add this to Phase 1. Its not a difficult or time consuming addition and I think it will not only make more sense to have a "landing page" of sorts, but set up the concept of the Dashboard for future releases.
