### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/techhub#46]
"We need to use the bar at the bottom to navigate to the right and to the left. Could you remove the Primary phone column to have the summary without navigating?"

Is this a viewport issue that can be fixed/adjusted so that horizontal scrolling is not necessary?

**Comment by Toddses** [comment]
related to #11

**Comment by ginfuru** [comment]
@Toddses Lets got ahead and knock this one out also.

**Comment by Toddses** [comment]
@ginfuru Okay I've got the majority of the work done here. Its decent down to 960px width, but once you drop below that we'd really need a mobile UI to keep the UX up to par. I need to do some more testing and tweaking and then I'll deploy to staging. I'll let you know when its up for a round of feedback.
