### ISSUE TITLE
Detailed Search

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/techhub#49]
"If I type “machining” in the detailed search, I have no result either – see the picture below"
![unnamed](https://cloud.githubusercontent.com/assets/12190207/10223864/400d6eda-6829-11e5-893d-284df7c4265a.jpg)

**Comment by Toddses** [comment]
Need to discuss this a bit. Detailed search doesn't currently search the taxonomies (category, process, county, volume, material). That's what the tag-based search is doing. If we allow detailed search to search everything, that essentially makes the tag based search duplicate functionality.

**Comment by Toddses** [comment]
Change the language for the detailed search box.
