### ISSUE TITLE
Apparent Missing Selection/Mandatory Field

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/techhub#52]
Please refer to the website fields.xlsx document that was sent to ensure that all mandatory fields are mandatory and that all fields are reproduced on the website. For instance (not exhaustive): The certification field is mandatory. The category is mandatory. The sector is mandatory. Material can have multiple selections. There is no field for the products (mandatory).

**Comment by ginfuru** [comment]
@jonathanhauge that `website fields.xlsx` document is not the correct document to be used. file `v2-supplier-database` is the correct file to be used.

**Comment by ginfuru** [comment]
This is related to #51
