### ISSUE TITLE
Saved Supplier, how to Edit?

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/techhub#54]
I saved a supplier but it is created. The status should be draft and I should be able to edit it. How?

**Comment by Toddses** [comment]
So newly created suppliers should not be published until they are approved by someone?

**Comment by jonathanhauge** [comment]
I disagree with their logic, I can defend that one and suggest that they
just edit it while it's LIVE.


ᐧ

-- 
Jonathan Hauge


marketing - branding - design - communications - digital

*A 2012 BBB Eclipse Integrity Award Finalist*

937 / 490-4005
1360 Technology Court  |  Suite 300  |  Beavercreek, OH 45430
www.baldwincreative.com

Confidentiality Notice: This email message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message.

**Comment by Toddses** [comment]
I agree its probably not a big deal to just edit a live supplier. It just depends on if they want to take the time to have an approval process for new suppliers.

**Comment by ginfuru** [comment]
**reference:** #66

**Comment by ginfuru** [comment]
@Toddses We'll need to add this prior to the `1/19/16` **See Slack**
